services:
  mysql:
    image: mysql:latest
    container_name: wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wallet_db
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: wallet_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      timeout: 20s
      retries: 10
      interval: 10s

  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wallet_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: wallet_user
      SPRING_DATASOURCE_PASSWORD: wallet_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wallet-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  wallet-network:
    driver: bridge